venturenative-api:
    build: .
    dockerfile: Dockerfile.local
    environment:
        - NODE_ENV=local
    volumes:
        - .:/app
        - /app/node_modules
    ports:
        - '3000:3000'
    restart: on-failure
