branch-defaults:
  master:
    environment: vn-api-prod
global:
  application_name: venture Native API
  default_ec2_keyname: mike
  default_platform: 64bit Amazon Linux 2016.03 v2.1.6 running Docker 1.11.2
  default_region: us-east-1
  profile: eb-cli
  sc: git
